<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNuR8ydx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNuR8ydx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNuR8ydx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNuR8ydx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNuR8ydx\App_KernelDevDebugContainer([
    'container.build_hash' => 'NuR8ydx',
    'container.build_id' => '9ef1af71',
    'container.build_time' => 1607788947,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNuR8ydx');
