<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'prod_desc_index' => [[], ['_controller' => 'App\\Controller\\ProdDescController::index'], [], [['text', '/prod/descriere/']], [], []],
    'prod_desc_new' => [[], ['_controller' => 'App\\Controller\\ProdDescController::new'], [], [['text', '/prod/descriere/new']], [], []],
    'prod_desc_show' => [['id'], ['_controller' => 'App\\Controller\\ProdDescController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/prod/descriere']], [], []],
    'prod_desc_edit' => [['id'], ['_controller' => 'App\\Controller\\ProdDescController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/prod/descriere']], [], []],
    'prod_desc_delete' => [['id'], ['_controller' => 'App\\Controller\\ProdDescController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/prod/descriere']], [], []],
    'tara_prod_index' => [[], ['_controller' => 'App\\Controller\\TaraProdController::index'], [], [['text', '/tara/prod/']], [], []],
    'tara_prod_new' => [[], ['_controller' => 'App\\Controller\\TaraProdController::new'], [], [['text', '/tara/prod/new']], [], []],
    'tara_prod_show' => [['id'], ['_controller' => 'App\\Controller\\TaraProdController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/tara/prod']], [], []],
    'tara_prod_edit' => [['id'], ['_controller' => 'App\\Controller\\TaraProdController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/tara/prod']], [], []],
    'tara_prod_delete' => [['id'], ['_controller' => 'App\\Controller\\TaraProdController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/tara/prod']], [], []],
];
